# Generated by Django 4.2.1 on 2023-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0004_mymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="upload_file",
            field=models.FileField(upload_to="media/"),
        ),
    ]
